# Generated by Django 5.2 on 2026-10-03 12:17

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Ключ в JSON. Оставьте пустым — создастся автоматически. После создания не меняется.', max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]*$', 'Только латиница в нижнем регистре, цифры и _, начинается с буквы.')], verbose_name='Код')),
                ('data_type', models.CharField(choices=[('text', 'Текст'), ('int', 'Целое число'), ('decimal', 'Число (дробное)'), ('bool', 'Да / Нет'), ('choice', 'Выбор из списка (одно значение)'), ('multi', 'Выбор из списка (несколько значений)')], max_length=16, verbose_name='Тип')),
                ('unit', models.CharField(blank=True, max_length=16, verbose_name='Ед. измерения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Бренд / производитель')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]*$', 'Только латиница в нижнем регистре, цифры и _, начинается с буквы.')], verbose_name='Код')),
                ('label', models.CharField(max_length=128, verbose_name='Подпись')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.attribute')),
            ],
            options={
                'verbose_name': 'Вариант значения',
                'verbose_name_plural': 'Варианты значений',
                'ordering': ['sort_order', 'label'],
                'constraints': [models.UniqueConstraint(fields=('attribute', 'code'), name='uniq_option_code_per_attr')],
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательна')),
                ('is_filterable', models.BooleanField(default=True, verbose_name='Показывать в фильтре')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_links', to='shop.attribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_links', to='shop.category')),
            ],
            options={
                'verbose_name': 'Характеристика категории',
                'verbose_name_plural': 'Характеристики категории',
                'ordering': ['sort_order'],
                'constraints': [models.UniqueConstraint(fields=('category', 'attribute'), name='uniq_attr_per_category')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Slug')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(blank=True, help_text='Пусто = цена по запросу', null=True, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='Характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='product_cat_active_idx'), django.contrib.postgres.indexes.GinIndex(fields=['attributes'], name='product_attrs_gin', opclasses=['jsonb_path_ops'])],
            },
        ),
    ]
