# Generated by Django 5.2 on 2026-10-08 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySortRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=80, verbose_name='Сортировать по')),
                ('descending', models.BooleanField(default=False, verbose_name='По убыванию')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sort_rules', to='shop.category')),
            ],
            options={
                'verbose_name': 'Правило сортировки',
                'verbose_name_plural': 'Правила сортировки выдачи',
                'ordering': ['sort_order'],
            },
        ),
    ]
